name: Simple Test

on:
  push:
    branches: [ "main" ]

jobs:
  test_parser:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Workflow Parser
        run: echo "The workflow parser is  working!"
